
---
- hosts: webservers
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Apache
      apt: name=apache2 update_cache=yes

    - name: Install PostgreSQL
      apt: name=postgresql update_cache=yes

    - name: Ensure Aache is Running
      service:
        name: apache2
        state: started
        enabled: true

    - name: ensure Postgres Is Running
      service:
        name: postgres
        state: started
        enabled: true