
---
- hosts: webservers
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Apache
      apt: name=apache2 update_cache=yes

    - name: Remove PostgreSQL
      apt:
        name: postgresql
        state: absent

    - name: Remove Prometheus
      apt:
        name: prometheus
        state: absent

    - name: Install MariaDB Server
      apt:
        name: mariadb-server
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Ensure Apache is Running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Ensure MariaDB is Running
      service:
        name: myslq
        state: started
        enabled: true