---
- hosts: common
  become: yes
  remote_user: adminfpi
  gather_facts: no
  tasks:

#### SECURITY COMPLIANCE ###########################################

    - name: Wheel Group Control
      group:
        name: wheel
        state: present

    - name: Passwordless Sudo For Wheel Group
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add User to Wheel Group
      user:
        name=adminfpi
        groups=wheel
        append=yes
        state=present
        createhome=yes

    - name: Set up Keys for Adminfpi
      authorized_key: user=adminfpi state=present key="{{ item }}"
      no_log: true
      with_file:
        - /home/adminfpi/.ssh/id_rsa.pub

#### INSTALL APPS ###########################################

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Install Python
      apt: name=net-tools update_cache=yes

    - name: Install Net-Tools
      apt: name=net-tools update_cache=yes

    - name: Install Nmap
      apt: name=nmap update_cache=yes

    - name: Install Members Utility
      apt: name=members update_cache=yes

#### INSTALL SERVER SERVICES ################################

    - name: Install SSH Server
      apt: name=openssh-server update_cache=yes

    - name: Install Firewall
      apt: name=ufw update_cache=yes

    - name: Set logging
      ufw:
        logging: 'on'

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable UFW
      ufw:
        state: enabled

    - name: SSH Server Control
      service:
        name: ssh
        state: started
        enabled: true