- name: Create Instance
  hosts: localhost
  gather_facts: yes
  vars:
    gcp_project: iaac-237416
    gcp_cred_kind: serviceaccount
    gcp_compute_zone: europe-west6-b
    gcp_machine_type: e2-micro
    gcp_source_image: "projects/debian-cloud/global/images/debian-10-buster-v20200805"
    gcp_auth_kind: serviceaccount
    gcp_service_account_email: provision@iaac-237416.iam.gserviceaccount.com
    gcp_service_account_file: /home/adminfpi/secure/iaac-237416-079a839e9e0c.json
    gcp_zone: 'europe-west6-b'
    gcp_region: 'europe-west6'
    network: 'default'

  tasks:

#### CREAT LABSRV10 ##############################################

    - name: Create Disk
      gcp_compute_disk:
        name: labsrv10
        size_gb: 10
        source_image: "{{ gcp_source_image }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: disk

    - name: Create VPC Network
      gcp_compute_network:
        name: "{{ network }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: network

    - name: Create Address
      gcp_compute_address:
        name: labsrv10
        address_type: INTERNAL
        address: 10.172.0.36
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: address

    - name: Create Instance
      gcp_compute_instance:
        name: labsrv10
        machine_type: "{{ gcp_machine_type }}"
        metadata:
          from_file: install_python.sh
          startup-script: "#! /bin/bash\n\n# Installs Python\napt update\napt -y install python"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
          network_ip: 10.172.0.36
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present

### CREAT LABSRV11 ##############################################

    - name: Create Disk
      gcp_compute_disk:
        name: labsrv11
        size_gb: 10
        source_image: "{{ gcp_source_image }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: disk

    - name: Create Address
      gcp_compute_address:
        name: labsrv11
        address_type: INTERNAL
        address: 10.172.0.37
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: address

    - name: Create Instance
      gcp_compute_instance:
        name: labsrv11
        machine_type: "{{ gcp_machine_type }}"
        metadata:
          from_file: install_python.sh
          startup-script: "#! /bin/bash\n\n# Installs Python\napt update\napt -y install python"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
          network_ip: 10.172.0.37
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present

### CREAT LABSRV12 ##############################################

    - name: Create Disk
      gcp_compute_disk:
        name: labsrv12
        size_gb: 10
        source_image: "{{ gcp_source_image }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: disk

    - name: Create Address
      gcp_compute_address:
        name: labsrv12
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: address

    - name: Create Instance
      gcp_compute_instance:
        name: labsrv12
        machine_type: "{{ gcp_machine_type }}"
        metadata:
          from_file: install_python.sh
          startup-script: "#! /bin/bash\n\n# Installs Python\napt update\napt -y install python"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
          network_ip: 10.172.0.38
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present

### CREAT LABSRV13 ##############################################

    - name: Create Disk
      gcp_compute_disk:
        name: labsrv13
        size_gb: 10
        source_image: "{{ gcp_source_image }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: disk

    - name: Create Address
      gcp_compute_address:
        name: labsrv13
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: address

    - name: Create Instance
      gcp_compute_instance:
        name: labsrv13
        machine_type: "{{ gcp_machine_type }}"
        metadata:
          from_file: install_python.sh
          startup-script: "#! /bin/bash\n\n# Installs Python\napt update\napt -y install python"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
          network_ip: 10.172.0.39
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present