# Example Playbook
- name: Google Cloud Create Instances
  hosts: localhost
  tasks:

    - name: create a instance
      gcp_compute_instance:
        name: labsrv05
        machine_type: e2-micro
        zone: europe-west6-b
        project: iaac-237416
        auth_kind: serviceaccount
        service_account_file: "iaac-237416-288184cdfda1.json"
        state: present