
---
- hosts: servers
  become: yes
  remote_user: adminfpi
  hosts: labsrv01

  Tasks:

    - name: Set GCP_AUTH_KIND variable
      shell: "echo $GCP_AUTH_KIND"
      environment:
        GCP_AUTH_KIND: serviceaccount
      register: GCP_AUTH_KIND

    - debug:
      var: GCP_AUTH_KIND.stdout

    - name: Set GCP_SERVICE_ACCOUNT_EMAIL variable
      shell: "echo $GCP_SERVICE_ACCOUNT_EMAIL"
      environment:
        GCP_SERVICE_ACCOUNT_EMAIL: provision@iaac-237416.iam.gserviceaccount.com
      register: GCP_SERVICE_ACCOUNT_EMAIL

    - debug:
      var: GCP_SERVICE_ACCOUNT_EMAIL.stdout

    - name: Set GCP_SERVICE_ACCOUNT_FILE variable
      shell: "GCP_SERVICE_ACCOUNT_FILE"
      environment:
        GCP_SERVICE_ACCOUNT_FILE: /home/adminfpi/secure/iaac-237416-1c777c9c8e68.json
      register: GCP_SERVICE_ACCOUNT_FILE

    - debug:
      var: GCP_SERVICE_ACCOUNT_FILE.stdout

##########################################################

  tasks:

  - name: Create a GCP instance
  hosts: localhost
  vars:
     gcp_project: iaac-237416
     gcp_cred_kind: serviceaccount
     gcp_compute_zone: europe-west6-b
     gcp_machine_type: e2-micro
     gcp_source_image: debian-10-buster-v20200805
     gcp_service_account_file: /home/adminfpi/secure/iaac-237416-1c777c9c8e68.json
    
    - name: Create A  VPC Network
      gcp_compute_network:
        name: network-instance
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
      register: network