- name: Create a GCP instance
  hosts: localhost
  vars:
     gcp_project: iaac-237416
     gcp_cred_kind: serviceaccount
     gcp_compute_zone: europe-west6-b
     gcp_machine_type: e2-micro
     gcp_source_image: debian-10-buster-v20200805

  tasks:

    - name: Create A  VPC Network
      gcp_compute_network:
        name: network-instance
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: network