---
- hosts: Build_Server
  become: yes
  remote_user: adminfpi

# INSTALL JAVA ##########################

  tasks:
    - name: Setup OpenJDK Repository
      apt_repository:
        repo: 'ppa:openjdk-r/ppa'
      become: true

    - name: Install OpenJDK 14
      apt:
        name:
          - openjdk-14-jdk
        state: present
        update_cache: 'yes'
      become: true

    - name: Set Java Path
      set_fact:
        java_path: /usr/lib/jvm/java-1.14.0-openjdk-amd64

# INSTALL JENKINS ######################

    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Jenkins Repository Keys
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins Source
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://pkg.jenkins.io/debian-stable binary/
        create: yes

    - name: Update Cache
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Jenkins
      apt:
        name:
          - jenkins
        state: present
      become: true

#     action: shell wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

#   - name: install Jenkins
#     apt: name=Jenkins update_cache=yes state=latest
#
#   - name: ensure Jenkins Server is running
#     service:
#       name: Jenkins
#       state: started
#       enabled: true
