---
- hosts: monitor
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Install Jenkins Repository Keys
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present