---
- hosts: monitor
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Add ElasticSearch Source
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        create: yes

    - name: Install ElasticSearch Keys
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Update Cache
      apt:
        update_cache=yes

    - name: Install ElasticSearch
      apt:
        name:
          - elasticsearch
        state: present