---
- hosts: monitor
  become: yes
  remote_user: adminfpi
  tasks:

    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

# INSTALL JAVA #########################

    - name: Setup OpenJDK Repository
      apt_repository:
        repo: 'ppa:openjdk-r/ppa'
        state: present
        update_cache: true

    - name: Install OpenJDK
      apt:
        name:
          - openjdk-8-jre
        state: present
        update_cache: true

    - name: Set Java Path
      set_fact:
        java_path: /usr/lib/jvm/java-1.8.0-openjdk-amd64

# INSTALL ElasticSearch #####################################

    - name: Add ElasticSearch Source
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        create: yes

    - name: Install ElasticSearch Keys
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Install ElasticSearch
      apt:
        name:
          - elasticsearch
        state: present

    - name: Add ElasticSearch IP
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: "network.host: 192.168.10.108"
        create: yes

    - name: Add ElasticSearch Port
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: "http.port: 9200"
        create: yes

    - name: ensure ElasticSearch is running
      service:
        name: elasticsearch
        state: started
        enabled: true

# INSTALL NGINX #############################################

    - name: Install Nginx
      apt:
        name:
          - nginx
        state: present

    - name: ensure Kibana is running
      service:
        name: nginx
        state: started
        enabled: true

# INSTALL KIBANA #############################################

    - name: Install Kibana
      apt:
        name:
          - kibana
        state: present

    - name: ensure Kibana is running
      service:
        name: kibana
        state: started
        enabled: true

# INSTALL LOGSTASH #############################################

    - name: Install LogStash
      apt:
        name:
          - logstash
        state: present

    - name: ensure LogStash is running
      service:
        name: logstash
        state: started
        enabled: true

# INSTALL Filebeat #############################################

    - name: Install Filebeat
      apt:
        name:
          - filebeat
        state: present

    - name: ensure Kibana is running
      service:
        name: filebeat
        state: started
        enabled: true

# ElasticSearch FIREWALL ######################################

    - name: Enable UFW And Deny All
      ufw:
        state: enabled
        policy: deny

    - name: Set Logging
      ufw:
        logging: 'on'

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH
        src: 192.168.10.0/24

    - name: Allow ElasticSearch tcp port 9200
      ufw:
        rule: allow
        port: '9200'
        proto: tcp
        src: 192.168.10.0/24