---
- hosts: monitor
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Add ElasticSearch Source
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://pkg.jenkins.io/debian-stable binary/
        create: yes

    - name: Install ElasticSearch Keys
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Install ElasticSearch
      apt:
        name: elasticsearch
        state: present
        update_cache=yes