---
- hosts: monitor
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Add Jenkins Source
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://pkg.jenkins.io/debian-stable binary/
        create: yes