---
- hosts: servers
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: install net-tools
      apt: name=net-tools update_cache=yes

    - name: Install SSH Server
      apt: name=openssh-server update_cache=yes

    - name: ensure SSH Server is running
      service:
        name: ssh
        state: started
        enabled: true

    - name: install Members
      apt: name=members update_cache=yes