---
- hosts: servers
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: install net-tools
        apt: name=net-tools update_cache=yes state=latest

    - name: Install SSH Server
      apt: name=openssh-server update_cache=yes state=latest

    - name: ensure SSH Server is running
      service:
        name: ssh
        state: started
        enabled: true