---
- hosts: servers
  become: yes
  remote_user: adminfpi
  tasks:

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add sudoers users to wheel group
      user:
        name=adminfpi
        groups=wheel
        append=yes
        state=present
        createhome=yes

    - name: Set up authorized keys for the adminfpi user
      authorized_key: user=adminfpi state=present key="{{ item }}"
      with_file:
        - /home/adminfpi/.ssh/id_rsa.pub

    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: install net-tools
      apt: name=net-tools update_cache=yes

    - name: Install SSH Server
      apt: name=openssh-server update_cache=yes

    - name: ensure SSH Server is running
      service:
        name: ssh
        state: started
        enabled: true

    - name: install Members
      apt: name=members update_cache=yes