
---
- hosts: web
  become: yes
  remote_user: adminfpi
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Apache
      apt: name=apache2 update_cache=yes

    - name: Remove PostgreSQL
      apt:
        name: postgresql
        state: absent

    - name: Remove Prometheus
      apt:
        name: prometheus
        state: absent

    - name: Install MariaDB Server
      apt:
        name: mariadb-server
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Ensure Apache is Running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Ensure MariaDB is Running
      service:
        name: mysql
        state: started
        enabled: true

# FIREWALL RULE #######################

    - name: Enable UFW And Deny All
      ufw:
        state: enabled
        policy: deny

    - name: Set Logging
      ufw:
        logging: 'on'

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH
        src: 192.168.10.0/24
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow all access to tcp port 443
      ufw:
        rule: allow
        port: '443'
        proto: tcp