---
- hosts: web
  become: yes
  remote_user: adminfpi
  vars:
    http_port: 80
    domain: fpittelo.ch
  tasks:
#   - name: Install prerequisites
#    apt: name={{ item }} update_cache=yes force_apt_get=yes
#     loop: [ 'aptitude' ]

#   - name: Remove PostgreSQL
#     apt:
#       name: postgresql
#       state: absent

#   - name: Remove Prometheus
#     apt:
#       name: prometheus
#       state: absent

#### INSTALL APPS SERVICES ##################

    - name: Install Git
      apt: name=git update_cache=yes

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install Lynx
      apt:
        name: lynx
        state: present

#### INSTALL MARRI DB SERVER ################

    - name: Install MariaDB Server
      apt:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB is Running
      service:
        name: mysql
        state: started
        enabled: true

#### INSTALL APACHE #########################

    - name: Install Apache
      apt: name=apache2 update_cache=yes

    - name: Enable mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: Apache2 Listen On Port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: Apache2 Virtualhost On Port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2

    - name: Create Virtual Host File
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

#   - name: Stop Default Apache Site
#     command: a2dissite 000-default.conf
#     notify:
#       - restart apache2

    - name: Enable Virtual Host {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2

# handlers:
#   - name: restart apache2
#     service: name=apache2 state=restarted

    - name: Ensure Apache is Running
      service:
        name: apache2
        state: started
        enabled: true

# FIREWALL RULE #############################

    - name: Enable UFW And Deny All
      ufw:
        state: enabled
        policy: deny

    - name: Set Logging
      ufw:
        logging: 'on'

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow all access to tcp port 443
      ufw:
        rule: allow
        port: '443'
        proto: tcp

#### DEPLOY WEBSITE FROM GITHUB #########################

    - name: Clone Git Website
      git:
        repo: 'https://github.com/fpittelo/website.git'
        dest: /var/www/labsite
        update: no
        version: master

#### WEB PAGE VERIFICATION ##############################

    - name: Check Page status 200 And Word "Solutions" Is In The Webpage
      uri:
        url: http://{{ ansible_host }}:{{ http_port }}
        return_content: yes
      register: this
      failed_when: "Solutions"

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted