---
- hosts: build
  become: yes
  remote_user: adminfpi
  tasks:

# INSTALL JAVA #########################

  tasks:
    - name: Setup OpenJDK Repository
      apt_repository:
        repo: 'ppa:openjdk-r/ppa'
      become: true

    - name: Install OpenJDK
      apt:
        name:
          - openjdk-8-jre
        state: present
        update_cache: 'yes'
      become: true

    - name: Set Java Path
      set_fact:
        java_path: /usr/lib/jvm/java-1.8.0-openjdk-amd64

# INSTALL JENKINS ######################

    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Jenkins Repository Keys
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins Source
      lineinfile:
        path: /etc/apt/sources.list
        line: deb https://pkg.jenkins.io/debian-stable binary/
        create: yes

    - name: Update Cache
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Jenkins
      apt:
         name:
           - jenkins
         state: present
      become: true

    - name: ensure Jenkins is running
      service:
        name: jenkins
        state: started
        enabled: true

# JENKINS FIREWALL ######################################

    - name: Enable UFW And Deny All
      ufw:
        state: enabled
        policy: deny

    - name: Set Logging
      ufw:
        logging: 'on'

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH
        src: 192.168.10.0/24
    - name: Allow Jenkins tcp port 8080
      ufw:
        rule: allow
        port: '8080'
        proto: tcp
        src: 192.168.10.0/24

##### INSTALL ANSIBLE ###################################

    - name: Install Ansible
      apt: name=ansible update_cache=yes

    - name: Copy Ansible Hosts File
      copy:
        src: /etc/ansible/hosts
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Copy Ansible Hosts File
      copy:
        src: /home/adminfpi/iaac/ANSIBLE/servers.yml
        dest: /home/adminfpi/servers.yml