---
- hosts: servers
  become: yes
  remote_user: adminfpi
  tasks:

    - name: Wheel Group Control
      group:
        name: wheel
        state: present

    - name: Passwordless Sudo For Wheel Group
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add User to Wheel Group
      user:
        name=adminfpi
        groups=wheel
        append=yes
        state=present
        createhome=yes

    - name: Set up Keys for Adminfpi
      authorized_key: user=adminfpi state=present key="{{ item }}"
      with_file:
        - /home/adminfpi/.ssh/id_rsa.pub

    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Net-Tools
      apt: name=net-tools update_cache=yes

    - name: Install SSH Server
      apt: name=openssh-server update_cache=yes

    - name: Install Firewall
      apt: name=ufw update_cache=yes

    - name: UFW Service Control
      service:
        name: ufw
        state: enable
        enabled: true

    - name: SSH Server Control
      service:
        name: ssh
        state: started
        enabled: true

    - name: Install Members Utility
      apt: name=members update_cache=yes