---
- hosts: servers
  become: yes
  remote_user: adminfpi
  tasks:

#### SECURITY COMPLIANCE ###########################################

    - name: Wheel Group Control
      group:
        name: wheel
        state: present

    - name: Passwordless Sudo For Wheel Group
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add User to Wheel Group
      user:
        name=adminfpi
        groups=wheel
        append=yes
        state=present
        createhome=yes

    - name: Set up Keys for Adminfpi
      authorized_key: user=adminfpi state=present key="{{ item }}"
      with_file:
        - /home/adminfpi/.ssh/id_rsa.pub

#### INSTALL APPS ###########################################

    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Net-Tools
      apt: name=net-tools update_cache=yes

    - name: Install Nmap
      apt: name=nmap update_cache=yes

    - name: Install Members Utility
      apt: name=members update_cache=yes

#### INSTALL SERVER SERVICES ################################

    - name: Install SSH Server
      apt: name=openssh-server update_cache=yes

    - name: Install Firewall
      apt: name=ufw update_cache=yes

    - name: Set logging
      ufw:
        logging: 'on'

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH
        src: 192.168.10.0/24

    - name: Enable UFW
      ufw:
        state: enabled

    - name: SSH Server Control
      service:
        name: ssh
        state: started
        enabled: true

###### EMAIL NOTIFICATION

    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: smtp.gmail.com
        port: 587
        username: frederic.pitteloud@gmail.com
        password: kboaolwwglzhoyeq
        to: Fred <frederic.pitteloud@gmail.com>
        subject: Ansible Report For Servers Policy
        body: System {{ ansible_hostname }} has been successfully provisioned.
      delegate_to: labsrv01