
---
- hosts: web
  become: yes
  remote_user: adminfpi
  tasks:
#   - name: Install prerequisites
#    apt: name={{ item }} update_cache=yes force_apt_get=yes
#     loop: [ 'aptitude' ]

#   - name: Remove PostgreSQL
#     apt:
#       name: postgresql
#       state: absent

#   - name: Remove Prometheus
#     apt:
#       name: prometheus
#       state: absent

#### INSTALL SERVER SERVICES ################################

    - name: Install Apache
      apt: name=apache2 update_cache=yes

    - name: Install MariaDB Server
      apt:
        name: mariadb-server
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Ensure Apache is Running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Ensure MariaDB is Running
      service:
        name: mysql
        state: started
        enabled: true

# FIREWALL RULE #######################

    - name: Enable UFW And Deny All
      ufw:
        state: enabled
        policy: deny

    - name: Set Logging
      ufw:
        logging: 'on'

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH
        src: 192.168.10.0/24

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow all access to tcp port 443
      ufw:
        rule: allow
        port: '443'
        proto: tcp

#### WEB PAGE VERIFICATION

    - name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
      uri:
        url: http://labsrv03
        return_content: yes
      register: this
      failed_when: "'Ubuntu' not in this.content"

###### EMAIL NOTIFICATION

    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: smtp.gmail.com
        port: 587
        username: frederic.pitteloud@gmail.com
        password: kboaolwwglzhoyeq
        to: Fred <frederic.pitteloud@gmail.com>
        subject: Ansible Report For Servers Policy
        body: System {{ ansible_hostname }} has been successfully provisioned.
      delegate_to: labsrv02